### ISSUE TITLE
Redo UI

### ISSUE THREAD

**Issue by joakimskoog** [joakimskoog/AnApiOfIceAndFire#112]
The UI is quite boring and could need some sprucing up.

**Comment by juleux** [comment]
Not sure what you mean by UI.  Are you looking to update the documentation at https://anapioficeandfire.com/ ?  If so, I may be able to help.

**Comment by joakimskoog** [comment]
Hello Julie,

I've actually started to work on upgrading the whole project to use the ASP.NET Core platform. While I'm doing that I'm also redoing the whole UI, you can check out my work at https://github.com/joakimskoog/AnApiOfIceAndFire/tree/upgrade-to-dotnet_core

I've only started to fix the UI on the start page and you're really welcome to come up with something better. I'm also open for any ideas since I'm pretty lousy at UI stuff. :)

**Comment by juleux** [comment]
Joakim:

Let me show you what I have been working on and fill you in on how I might be able to help with your UI.  I discovered your API while looking for a documentation project.  I wanted something fun that would enable me to show potential employers that I can use the latest tools.  Since then, I have been developing an updated version of your Documentation page.  You can see the latest version http://test.juleux.com/.  

I realize my updates are somewhat of an overkill.  That said, it would be relatively easy to add my version of the Documentation page to your site if you so choose.  The question for you would be whether or not you want to maintain something new.  I used a tool called Redoc https://github.com/Rebilly/ReDoc  which converts a yaml (or JSON) file into a tri-pane formatted page.  I am currently using the Redoc CDN, but there are other implementation options.  My files are located at https://github.com/juleux/Ice-and-Fire-API.  Let me know if you are interested. I would be happy to make adjustments as needed.

As for the remainder of your UI, I would love to contribute if I can.  However, after  looking at the link you sent me, I realized that your code is server-side (I am new to open source and still getting the hang of things).  I have the skills to redevelop your site in html – but not cshtml which is what I presume you would prefer.  Short of handing you a complete site, if there is something specific you need – some css, graphics, a layout, for example, just let me know and I’ll see what I can do.

Regards, Julie

**Comment by joakimskoog** [comment]
Julie:

That looks similar to what Stripe has (https://stripe.com/docs/api), it's also something I've been thinking about emulating. The one you linked looks great, good job! I've just got a few questions:
- What are the hosting options? Can we host it on anapioficeandfire.com?
- Is it possible to get the .HTML, .JS and .CSS files at compile time or is everything rendered at run time?

Regarding the .CSHTML-files: Yes, they are used server-side but it shouldn't be a problem (if you're thinking about if you need to learn C#) since I only use regular HTML in those files. Only problem is that you would need dotnet core (https://www.microsoft.com/net/core#windows) to run the whole project.

**Comment by juleux** [comment]
Joakim:

Great, glad you are happy with the docs.

To answer your questions:
-   What are the hosting options? Can we host it on anapioficeandfire.com?  Yes – I was able to install it on my Windows system with npm/node.
-   Is it possible to get the .HTML, .JS and .CSS files at compile tile or are the whole page rendered at run time?  Currently, you can only get pages rendered at run time.  There is a feature request for a precompile option which I agree would be preferable:  https://github.com/Rebilly/ReDoc/issues/124

When I get a chance, I will see if I can install .NET core.  It’s been a while since I have used .NET.

Julie

**Comment by joakimskoog** [comment]
A new UI is live on the site and exists in https://github.com/joakimskoog/AnApiOfIceAndFire/tree/aspnetcore11-port
