### ISSUE TITLE
Add character image

### ISSUE THREAD

**Issue by RNOVOSELOV** [joakimskoog/AnApiOfIceAndFire#119]
Add field wuth URL to the character's image or of the actor photo to the "character"-response

**Comment by iamtekeste** [comment]
This is really a great idea. But I don't think it is easy thing to do. @joakimskoog Do you have any guidance or idea on how to do this? I would love to help.

**Comment by joakimskoog** [comment]
This is a great suggestion that has been up for discussion earlier. I'll reiterate my concerns and thoughts regarding this feature down below:

- Host our own images or link to someone else's? If we use someone else's we'll link to their domain and that would, in my honest opinion, be quite rude since it can cost them quite a bit of bandwidth
- If we host our own, we need to get a hold on images for all characters. This can be quite easy, but all of them would have to be in the same theme. Meaning that we can't have a bunch of realistic images and then a bunch of cartoonish ones since that would look weird.
- There's also the issue with copyright. We need to only use images that we're allowed to use.

Before we start implementing this feature we need to answer the questions above.

**Comment by RNOVOSELOV** [comment]
1) According to copirates:
- I think that we need to use cartoonish characters images from "http://awoiaf.westeros.org" such as "http://awoiaf.westeros.org/index.php/File:Joshua_CairosJoff_Widows_Wail.jpg". Because there are images of all the characters there and will not need to be selected on various resources. Also "http://awoiaf.westeros.org" is already specified as the information provider on the "About" page of "AnApiOfIceAndFire" "https://anapioficeandfire.com/About" (Copyright section)
- Characters cartoonish pictures belong to Fantasy Flight Games. I am written to several designers of these images and they confirmed this. But they also said that for non-commercial use we can use images. We just need to give a link to the authors on the info page. See answers from designers below.
- 99% coast of arms pictures is licensed under the Creative Commons Attribution ShareAlike 3.0 License. In short: you are free to share and make derivative works of the file under the conditions that you appropriately attribute it, and that you distribute it only under a license identical to this one. Official license Subject to disclaimers.

Answers from designers:
* Joshua Cairos ("http://awoiaf.westeros.org/index.php/File:Joshua_CairosJoff_Widows_Wail.jpg")
HI!
Is only for use it in the pag ? Like westeros webpage ? Because fantasy flight games has the license of these illustration, but if is only for put in the web, I think that you can.
* Narwen Illustrations ("http://awoiaf.westeros.org/index.php/File:House_Baratheon.svg")
Hello, while proper credit information will posted I do not mind.
* Britt Martin ("http://awoiaf.westeros.org/index.php/File:Brittmartin_Theon.jpg")
Hi Roman
Many thanks for the request!
As long as this is not a commercial product (my illustrations were created for a game company - Green Ronin Publishing),
then you have permission to use them.
Thanks a lot!
britt

2) Host our own images or link to someone else's
I think it's more your question @joakimskoog, as the creator and architect of this API. Store your images of course more reliable.
Byt In my opinion, it's enough to give a link to the pictures on http: //awoiaf.westeros.org. I, like the android developer, will just correctly process the broken links and substitute the default picture in case the image is missing from the link. I do not think there will be a lot of traffic and their bandwidth should be enough. At least I will download pictures as they are viewed by the user and not all at once.

**Comment by joakimskoog** [comment]
I'm merging all discussions about images in this issue: https://github.com/joakimskoog/AnApiOfIceAndFire/issues/127
