### ISSUE TITLE
"died" should be an array

### ISSUE THREAD

**Issue by Mottie** [joakimskoog/AnApiOfIceAndFire#132]
Case in point... the example on https://anapioficeandfire.com/ is showing Jon Snow; and we all know what happened there!
<img title=":_onion_head_zomg:" src="https://cloud.githubusercontent.com/assets/136959/13371854/7227398c-dcf5-11e5-88be-0b8f969dd4e1.gif">

**Comment by joakimskoog** [comment]
Well, it kind of depends to be honest. Should we change the type of `Died` because a few characters has miraculously resurrected? Although I get your point, not populating the `Died`-field of a character has actually **died** may seem a bit wrong.

I'm not quite sure how to handle this to be honest, we can go either way.

**Comment by AllanOcelot** [comment]
This ties directly into #55 - As characters are alive or dead at certain times.

**Comment by joakimskoog** [comment]
Closed for now. Please open a new issue if this is still interesting.
