### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by hawkfalcon** [joakimskoog/AnApiOfIceAndFire#99]
All endpoints seem to be returning a 404 right now.

**Comment by joakimskoog** [comment]
Hello,

This is entirely my fault. I made a, sadly, breaking change to the versioning logic [yesterday](https://github.com/joakimskoog/AnApiOfIceAndFire/commit/3a8e636b8e36ab04304f48f9a544027fb993c3dd).

**Versioning before change:** If a request did not have an Accept header we would look for the default version of a resource,, where the default version would be the highest available.
**Versioning after change:** If a request does not have a correct Accept header we will return a 404. We will not try to find the default version.

This change is made visible through the changes in the documentation:

**Before:** 

> **Important:** If a version is not specified in the request the default version will be used. The default version may change in the future and can thus break the consumer's application. Make sure to **always** request a specific version in the `Accept` header as shown in the example below.

**After:**

> **Important:** If a version is not specified in the request the request will fail. Make sure to **always** request a specific version in the `Accept` header as shown in the example below.

I apologise if this caused any problems for you. I promise that there won't be any more changes to the underlying versioning logic in the future. :)

**Comment by joakimskoog** [comment]
We should probably include a better error message in the response if no header is provided in the request. Maybe something like **No Accept header present in the request, please refer to the official documentation on how to include it**?

**Comment by hawkfalcon** [comment]
I can see what you were going for with this change, but I think it will break more than it attempts to fix. Why not change the url scheme to /1/endpoint instead? This broke all example on the site, as well as the "try it out thing". 

This change forces us to change the header, for any request we do.

**Comment by joakimskoog** [comment]
Hello again,

I actually reverted the commit since it broke a fair few things and I'm at work so I don't have time to fix them. I'm not interested in using versioning as a part of the url scheme. My first thought was to either have users explicitly state the version in the header or use some sort of magic value that shows the server that you can handle the latest version; **VLatest**. This would prevent people to forget using headers in their requests, as an example. Although I think you made a fair point, and I will keep the versioning logic that was used before the change, to prevent existing clients to break (again).

A side note: The documentation explicitly warns you about not using a version in the header since your client **might** break when a new version is released, depending on what the changes are and how the client is implemented.

**Comment by joakimskoog** [comment]
Closing this since I reverted the changes that created the issue.
